### ISSUE TITLE
Прямая ссылка не доступна

### ISSUE THREAD

**Issue by develop-dvs** [AiratHalitov/airat-aibolit-update#4]
Можно выложить последнюю версию айболита?

**Comment by AiratHalitov** [comment]
> Прямая ссылка не доступна

Видимо всё - прямая ссылка больше не будет работать.
 
На этот случай я сделал бекап и закачал файлы в этот репозиторий.
Есть архив https://github.com/AiratHalitov/airat-aibolit-update/blob/main/ai-bolit-hoster-backup.zip
и он же распакован в репозитории в папки 
https://github.com/AiratHalitov/airat-aibolit-update/tree/main/ai-bolit
и
https://github.com/AiratHalitov/airat-aibolit-update/tree/main/tools 

То есть не нужно запускать скрипт https://github.com/AiratHalitov/airat-aibolit-update/blob/main/airat-aibolit-update.sh
Можно сразу запускать https://github.com/AiratHalitov/airat-aibolit-update/blob/main/ai-bolit/run-aibolit.sh
в нужной папке.

**Comment by develop-dvs** [comment]
readme.md ещё обновите. Это очень полезная информация, кажется кроме вашего репозитория, актуальной версии больше нигде нет

**Comment by AiratHalitov** [comment]
Хорошо, обновлю чуть позже. Спасибо!)
